### ISSUE TITLE
关于图像中只有一个黑色，没有黄色球

### ISSUE THREAD

**Issue by BeStronger2021** [lyh-ADT/Shoots#3]
按照要求，打开local9999端口，但是却看不到黄色的球，只能看到黑色的球，然后也无法进行消灭，感觉结束不了游戏，请教一下，是为什么呐

**Comment by lyh-ADT** [comment]
默认情况下，黑色的是自己，黄色的是敌人。红色三角表示朝向，只有面对着敌人才可以看到敌人。可以用方向键来改变朝向。
你是找遍了整个地图都没看到黄色的球吗？

**Comment by BeStronger2021** [comment]
对的，我在每一个点上四个方向都试了一下，依旧看不到黄色的球

**Comment by lyh-ADT** [comment]
是这样的：
- master分支下面，每打开一个页面，就会添加一个玩家。也就是说如果想要看到另外的人，你需要再打开一个页面（其实说白了就是没有电脑玩家）。
- ai分支下面，只有电脑玩家，打开页面只能用于观战

**Comment by BeStronger2021** [comment]
那可以人和训练好的CFR互动吗

**Comment by lyh-ADT** [comment]
目前代码中没有实现，你可以fork项目，自己写一下。把CFRShooter添加到普通的Shoots里面就可以了

**Comment by BeStronger2021** [comment]
非常感谢，我试一下^-^
